### ISSUE TITLE
Unit Selection Bug

### ISSUE THREAD

**Issue by LanceGardner** [Eagleheart/Paralibrium#50]
I chose Amazon and it created Goblin Shaman

**Comment by Eagleheart** [comment]
First of all, lol.

Second of all, it took a while but I figured out what happened. The amazon failed, so it was really confusing. It turns out your dragon egg simply hatched into a goblin shaman. The unit numbers changed in the new list and that was previously the unit number of dragonling.

It is fixed now.

**Comment by LanceGardner** [comment]
hahahahahahaha ok
